version: "3.7"

services:
  app:
    build: ./app
    ports:
      - 4300:4300
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - api
    container_name: app_seed
  api:
    build: ./api
    ports:
      - 3007:3007
    volumes:
      - ./api:/api
      - /api/node_modules
    container_name: api_seed
